# graph 名称
name: "WordAgentService"

# graph 详细描述
description: "Word智能体网络"

# 为了完成任务的计划，通过调用 group 完成任务
groups:
  - WordAgentGroup

# 任务执行过程中的上下文信息（如返回值等），用于 group 之间的信息传递
context:
  - name: "task"
    type: "str"
  - name: "result"
    type: "str"
